[project]
name = "fastapi-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "fastapi[standard]>=0.141.1",
    "groq>=1.7.0",
    "httpx>=0.28.1",
    "imagekitio>=5.9.0",
    "mem0ai>=2.0.20",
    "njsparser>=2.16",
    "pydantic-settings>=2.15.0",
    "pygithub>=2.10.0",
    "pypdf>=6.16.2",
    "python-docx>=1.2.0",
    "python-multipart>=0.0.32",
    "uvicorn[standard]>=0.52.4",
]
